apiVersion: v2
name: mkdev-pgadmin
description: A Helm chart for pgAdmin
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: postgresql
    version: 10.13.14
    repository: https://charts.bitnami.com/bitnami
