apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image_name }}
          imagePullPolicy: {{ .Values.PullPolicy_image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
